---
title: "Homework2"
---

```{r include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)

```

```{r load_libraries}

library(tidyverse)

library(tidymodels)

library(glmnet)

```

```{r load_data}

heart = read_csv(here::here("data","heart.csv"))

```


## Ridge regression

```{r split_data}

heart_split = heart %>% 
  initial_split()

heart_train = heart_split %>% 
  training()

heart_test = heart_split %>% 
  testing()

heart_cv = heart_train %>% 
  vfold_cv(strata = "target")

penalty_grid = grid_regular(penalty(), levels = 100)


```


```{r set_model}

heart_ridge_mod = linear_reg(penalty = tune(),mixture = 0) %>%
  set_engine("glmnet")

heart_rec = recipe(target ~ ., data = heart_train)

heart_scaled_rec = recipe(target ~ ., data = heart_train) %>% 
  step_normalize(all_predictors())

ridge_wf = workflow() %>% 
  add_recipe(heart_rec) %>% 
  add_model(heart_ridge_mod)

ridge_scaled_wf = workflow() %>% 
  add_recipe(heart_scaled_rec) %>% 
  add_model(heart_ridge_mod)





```

```{r cross_validation}

ridge_cv = tune_grid(ridge_wf, grid = penalty_grid,
                     resamples = heart_cv)

ridge_scaled_cv = tune_grid(ridge_scaled_wf, grid = penalty_grid,
                     resamples = heart_cv)


```


```{r evaluate_cv}

ridge_cv %>% 
  show_best(metric = "rmse")

ridge_scaled_cv %>% 
  show_best(metric = "rmse")

```

## Ridge regression

```{r tidymodels_implementation}

heart_ridge_mod = linear_reg(penalty = tune(),mixture = 0) %>%
  set_engine("glmnet")

ridge_wf = workflow() %>% 
  add_recipe(heart_lin_rec) %>% 
  add_model(heart_ridge_mod)

penalty_grid = grid_regular(penalty(), levels = 50)

ridge_cv = tune_grid(ridge_wf, grid = penalty_grid,
                     resamples = vfold_cv(heart_train, v = 5))
ridge_cv %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_line() + 
  geom_point() + 
  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err)) + 
  scale_x_log10()


```

```{r glmnet_implementation}

glmnet_obj = glmnet(
  x = heart_train %>%
    select(-target) %>%
    as.matrix(),
  y = heart_train %>%
    select(target) %>%
    as.matrix(),
  alpha = 0
)

glmnet_cv = cv.glmnet(
  x = heart_train %>%
    select(-target) %>%
    as.matrix(),
  y = heart_train %>%
    select(target) %>%
    as.matrix(),
  alpha = 0
)


```

```{r plot_glmnet_log_lambda_coeffs}

plot(glmnet_obj,xvar = "lambda")

```

```{r plot_cv_glmnet}

plot(glmnet_cv)

```

